### ISSUE TITLE
java.sql.SQLException: Cannot operate as the connection has been closed

### ISSUE THREAD

**Issue by RahulJyala7** [zhicwu/cassandra-jdbc-driver#15]
i'm  creating multiple cassandra jdbc connection and getting Cannot operate as the connection has been closed error my full stacktrace here...

java.sql.SQLException: Cannot operate as the connection has been closed
	at com.github.cassandra.jdbc.CassandraErrors.connectionClosedException(CassandraErrors.java:37)
	at com.github.cassandra.jdbc.provider.datastax.CassandraConnection.validateState(CassandraConnection.java:445)
	at com.github.cassandra.jdbc.BaseCassandraConnection.rollback(BaseCassandraConnection.java:305)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:492)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.passivateObject(PoolableConnectionFactory.java:371)
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:578)
	at org.apache.commons.dbcp2.PoolableConnection.close(PoolableConnection.java:206)

**Comment by RahulJyala7** [comment]
I think I can change make a fix here by using pooling options correct me I'm wrong...
