### ISSUE TITLE
Exception in DBeaver eclipse plugin

### ISSUE THREAD

**Issue by binoydev** [zhicwu/cassandra-jdbc-driver#5]
eclipse : Neon.2
Dbeaver plugin : 4.0.2
cassandra : 2.2.9
cassandra-jdbc-driver : 0.6.2
java : 1.8

Caused by: java.lang.NullPointerException
	at com.github.cassandra.jdbc.BaseCassandraResultSet.getInt(BaseCassandraResultSet.java:413)
	at com.github.cassandra.jdbc.BaseCassandraResultSet.getInt(BaseCassandraResultSet.java:417)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getInt(JDBCResultSetImpl.java:501)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.safeGetInt(JDBCUtils.java:114)
	at org.jkiss.dbeaver.ext.generic.model.GenericUtils.safeGetInt(GenericUtils.java:80)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:142)
	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:128)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:220)
	at org.jkiss.dbeaver.ext.generic.model.GenericTable.getAttributes(GenericTable.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:793)
	... 11 more

**Comment by zhicwu** [comment]
Thanks for reporting this. With your detailed inputs, I can reproduce the issue on Dbeaver.

It turns out schema is somehow missing for all tables, which leads to an empty metadata in ResultSet. I'm not familiar with how Dbeaver works, looks like it handles schema in a different way compare to SquirrelSQL, which works just fine.

Anyway, before I can fix this issue, I think the workaround is to add schema name in your query. For example:
```sql
select * from system_traces.sessions limit 1
```
instead of the following:
```sql
select * from sessions limit 1
```

**Comment by zhicwu** [comment]
@binoydev, when you have time, could you try the [new build](https://github.com/zhicwu/cassandra-jdbc-driver/releases/tag/0.6.3-SNAPSHOT)? It should be working.

**Comment by binoydev** [comment]
@zhicwu You are the best. I checked and its working
I really appreciate your help for fixing the issue in such a short time.
