### ISSUE TITLE
Jdbc internal error 

### ISSUE THREAD

**Issue by SteveLuo8** [zhicwu/cassandra-jdbc-driver#9]
when using with dbeaver 4.2.4 with jdbc driver of 0.6.4, got Query execution failed

Internal jdbc driver error
  read timeout must be >= 0
  read timeout must be >= 0

what am i missing? 

Thanks

**Comment by zhicwu** [comment]
Do you have stack trace? Is the same query working in cqlsh?

**Comment by reith** [comment]
I faced same problem, stacktrace:
```
org.jkiss.dbeaver.model.exec.DBCException: SQL Error: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:141)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:181)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:92)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLException: Internal jdbc driver error
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.handleExecuteError(JDBCStatementImpl.java:313)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:347)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	... 4 more
Caused by: java.lang.IllegalArgumentException: read timeout must be >= 0
	at com.github.cassandra.jdbc.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.github.cassandra.jdbc.internal.datastax.driver.core.Statement.setReadTimeoutMillis(Statement.java:340)
	at com.github.cassandra.jdbc.provider.datastax.CassandraStatement.configureStatement(CassandraStatement.java:80)
	at com.github.cassandra.jdbc.provider.datastax.CassandraStatement.executeCql(CassandraStatement.java:122)
	at com.github.cassandra.jdbc.provider.datastax.CassandraStatement.execute(CassandraStatement.java:253)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	... 5 more
!SUBENTRY 1 org.jkiss.dbeaver.model 4 0 
```

**Comment by reith** [comment]
setting read_timeout by comment in cql shell makes query succeed

**Comment by zhicwu** [comment]
Thanks for the details @reith. I’ll try to fix it in the coming weekend.

There’s also an issue when converting read timeout from seconds to milliseconds, which should be fixed too.
